import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
    title: "FNP - Qatar",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex w-full">
                <Sidebar />
                <main className="w-full h-full">{children}</main>
            </body>
        </html>
    );
}
